complaint_manager:
    resource: "@HomoDemocraticoSapiensComplaintManagerBundle/Controller/DefaultController.php"
    type:     annotation
    
committee:
    resource: "@HomoDemocraticoSapiensComplaintManagerBundle/Controller/CommitteeController.php"
    type:     annotation
    
complaint:
    resource: "@HomoDemocraticoSapiensComplaintManagerBundle/Controller/ComplaintController.php"
    type:     annotation
